import nodemailer from 'nodemailer';

export default class MailServices {

   sendMail = (req) => {
      const { message, recipients, subject } = req;
      const transporter = nodemailer.createTransport({
         host: process.env.SMTP,
         port: process.env.MAIL_PORT,
         auth: {
            user: process.env.USER, //generated by Mailtrap
            pass: process.env.PASSWORD //generated by Mailtrap
         }
      });

      const mailOptions = {
         from: `"Afodamz" <${process.env.FROM}>`,
         to: recipients,
         subject,
         html: message
      }
      transporter.sendMail(mailOptions, (err, info) => {
         if (err) {
            return console.log(err);
         }
         console.log('Message sent: %s', info.messageId);
      })
   }

}